import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section
        style={{
          wordWrap: "break-word",
          overflowWrap: "break-word",
        }}
      >
        <h1>{JSON.stringify(session)}</h1>
      </section>
    </div>
  );
};

export default Home;
