import ProviderExample from "@/components/ProviderExample";
import Head from "next/head";
import HomePage from "../view/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProviderExample>
        <HomePage />
      </ProviderExample>
    </>
  );
}
